(function(){
'use strict';
const $=id=>document.getElementById(id);
const state={sb:null,user:null,store:{},content:{},vpnPlans:[],vpnPackages:[],premium:[],discounts:[],vpnFilter:'all',vpnQuery:'',drawerPlan:null,dirty:false,confirmResolve:null};
const paneMeta={overview:['Dashboard','داشبورد'],vpn:['Products / VPN','مدیریت VPN'],telegram:['Products / Telegram','Telegram'],pricing:['Commerce / Pricing','قیمت‌گذاری'],discounts:['Commerce / Discounts','تخفیف‌ها'],content:['Storefront / Content','محتوای فروشگاه'],store:['Storefront / Settings','تنظیمات فروشگاه'],audit:['System / Audit','تاریخچه تغییرات']};
function configured(){const c=window.BG_CONFIG||{};return /^https:\/\/.+\.supabase\.co/.test(c.SUPABASE_URL||'')&&(c.SUPABASE_PUBLISHABLE_KEY||'').length>20}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function num(v,d=0){const n=Number(v);return Number.isFinite(n)?n:d}
function fmt(v){return Number(v||0).toLocaleString('en-US',{maximumFractionDigits:2})}
function list(v){return [...new Set(String(v||'').split(/[،,\s]+/).map(Number).filter(n=>Number.isInteger(n)&&n>0))].sort((a,b)=>a-b)}
function jsonText(v){return JSON.stringify(v||[],null,2)}
function show(id,on=true){const el=$(id);if(el)el.classList.toggle('hidden',!on)}
function toast(message,type='success'){const host=$('toastHost');if(!host)return;const el=document.createElement('div');el.className='toast-msg '+type;el.textContent=message;host.appendChild(el);setTimeout(()=>{el.style.opacity='0';el.style.transform='translateY(8px)';setTimeout(()=>el.remove(),220)},2800)}
function setDirty(on=true){state.dirty=on;show('unsavedBadge',on)}
function errMessage(e){return e?.message||String(e||'خطای ناشناخته')}
async function confirmBox(title,text,yes='حذف'){const shell=$('confirmModal');$('confirmTitle').textContent=title;$('confirmText').textContent=text;$('confirmYes').textContent=yes;show('confirmModal',true);return new Promise(resolve=>{state.confirmResolve=resolve})}
function closeConfirm(result=false){show('confirmModal',false);if(state.confirmResolve){const r=state.confirmResolve;state.confirmResolve=null;r(result)}}
async function isAdmin(){const {data,error}=await state.sb.from('admin_users').select('user_id').eq('user_id',state.user.id).maybeSingle();if(error)throw error;return !!data}
const STORE_DEFAULTS={brand_name:'BlueGate',brand_subtitle:'Digital Services',hero_title:'سرویس‌های دیجیتال، ساده و سریع',hero_text:'VPN، تلگرام استارز و تلگرام پرمیوم با قیمت شفاف و سفارش مستقیم از پشتیبانی.',telegram_support:'bluegatesupport',telegram_channel:'BllueGate',footer_text:'سرویس‌های دیجیتال با پشتیبانی واقعی.',announcement_enabled:false,announcement_text:'',stars_price_basis:'usdt',star_base_usdt:.015,star_base_toman:2880,stars_markup:20,premium_markup:20,slider_min:50,slider_max:10000,slider_step:25,slider_presets:[100,500,1000,2500,5000],smart_rounding_enabled:true,round_small:5000,round_medium:10000,round_large:20000,fallback_usdt_toman:192000,show_reviews:false,show_tutorials:false,show_comparison:true};
const CONTENT_DEFAULTS={features:[],faq:[],reviews:[],tutorials:[],comparison:[]};
function adminNotice(title,text,type='warn'){const box=$('adminNotice');if(!box)return;$('adminNoticeTitle').textContent=title;$('adminNoticeText').textContent=text;box.className='admin-notice '+type}
function clearAdminNotice(){const box=$('adminNotice');if(box)box.className='admin-notice hidden'}
async function safeQuery(label,promise,fallback){try{const r=await promise;if(r.error)throw r.error;return {ok:true,data:r.data??fallback}}catch(e){console.error('[BlueGate Admin] '+label,e);return {ok:false,data:fallback,error:e}}}
async function loadAll(){
  clearAdminNotice();
  const sb=state.sb;
  const results=await Promise.all([
    safeQuery('store_settings',sb.from('store_settings').select('*').eq('id',1).maybeSingle(),null),
    safeQuery('content_settings',sb.from('content_settings').select('*').eq('id',1).maybeSingle(),null),
    safeQuery('vpn_plans',sb.from('vpn_plans').select('*').order('sort_order'),[]),
    safeQuery('vpn_packages',sb.from('vpn_packages').select('*').order('sort_order'),[]),
    safeQuery('premium_plans',sb.from('premium_plans').select('*').order('months'),[]),
    safeQuery('discount_codes',sb.from('discount_codes').select('*').order('created_at',{ascending:false}),[])
  ]);
  const [s,c,v,p,pr,d]=results;
  state.store={...STORE_DEFAULTS,...(s.data||{})};
  state.content={...CONTENT_DEFAULTS,...(c.data||{})};
  state.vpnPlans=Array.isArray(v.data)?v.data:[];
  state.vpnPackages=Array.isArray(p.data)?p.data:[];
  state.premium=Array.isArray(pr.data)?pr.data:[];
  state.discounts=Array.isArray(d.data)?d.data:[];
  try{renderAll()}catch(e){console.error('[BlueGate Admin] render',e);adminNotice('خطا در نمایش پنل',errMessage(e),'error');toast('خطا در نمایش پنل: '+errMessage(e),'error')}
  const failed=results.map((r,i)=>!r.ok?['store_settings','content_settings','vpn_plans','vpn_packages','premium_plans','discount_codes'][i]:null).filter(Boolean);
  if(failed.length)adminNotice('پنل با اطلاعات ناقص باز شد','دسترسی/جدول مشکل دارد: '+failed.join('، ')+' — Console را برای جزئیات ببین.','warn');
  setDirty(false);
}
function renderAll(){renderOverview();renderVpn();fillTelegram();renderPremium();renderDiscounts();fillContent();fillStore();renderPricing()}
function renderOverview(){$('adminEmail').textContent=state.user?.email||state.user?.id||'—';$('sessionInfo').textContent=state.user?.email||'Authenticated';$('kpiPlans').textContent=state.vpnPlans.length;$('kpiPremium').textContent=state.premium.length;$('kpiDiscounts').textContent=state.discounts.length;$('kpiRate').textContent=fmt(state.store.fallback_usdt_toman);$('sideVpnCount').textContent=state.vpnPlans.length;$('sidePremiumCount').textContent=state.premium.length}
function renderVpn(){const wrap=$('vpnEditor');if(!wrap)return;const q=state.vpnQuery.trim().toLowerCase();let plans=state.vpnPlans.filter(p=>{const f=state.vpnFilter==='all'||(state.vpnFilter==='active'&&p.active)||(state.vpnFilter==='inactive'&&!p.active);const s=!q||[p.title,p.slug,p.subtitle,p.note].some(x=>String(x||'').toLowerCase().includes(q));return f&&s});if(!plans.length){wrap.innerHTML='<div class="panel-card" style="grid-column:1/-1;text-align:center;color:#7f95a9">پلنی با این فیلتر پیدا نشد.</div>';return}wrap.innerHTML=plans.map(plan=>{const pk=state.vpnPackages.filter(x=>String(x.plan_id)===String(plan.id));const preview=pk.slice(0,3).map(x=>`<div><span>${esc(x.label)}</span><b>${fmt(x.price_toman)} ت</b></div>`).join('')+(pk.length>3?`<div><span>+ ${pk.length-3} پکیج دیگر</span><b>…</b></div>`:'');return `<article class="vpn-manage-card" data-plan-card="${plan.id}" data-theme="${esc(plan.theme||'blue')}"><div class="vpn-card-top"><div class="vpn-ident"><span class="icon">${esc(plan.icon||'🛡️')}</span><div><h3>${esc(plan.title)}</h3><p>${esc(plan.subtitle||'بدون توضیح')}</p></div></div><button class="more-btn" data-action="edit-plan" data-id="${plan.id}" title="ویرایش">•••</button></div><div class="vpn-meta"><span class="meta-chip ${plan.active?'active':'off'}">${plan.active?'● فعال':'● مخفی'}</span><span class="meta-chip">${pk.length} پکیج</span><span class="meta-chip">#${num(plan.sort_order)}</span></div><div class="vpn-package-preview">${preview||'<div><span>هنوز پکیجی ندارد</span><b>—</b></div>'}</div><div class="vpn-card-actions"><button class="btn soft" data-action="edit-plan" data-id="${plan.id}">ویرایش و پکیج‌ها</button><button class="btn ghost" data-action="toggle-plan" data-id="${plan.id}">${plan.active?'مخفی کن':'فعال کن'}</button></div></article>`}).join('')}
function openPlanDrawer(id=null){let plan=null;if(id!=null)plan=state.vpnPlans.find(x=>Number(x.id)===Number(id));state.drawerPlan=plan?{...plan}:{id:null,slug:'new-plan-'+Date.now(),title:'پلن جدید',subtitle:'',note:'',theme:'blue',icon:'🛡️',pills:[],sort_order:state.vpnPlans.length+1,active:true};$('drawerTitle').textContent=plan?'ویرایش '+plan.title:'پلن VPN جدید';$('planId').value=plan?.id||'';$('planTitle').value=state.drawerPlan.title;$('planSlug').value=state.drawerPlan.slug;$('planSubtitle').value=state.drawerPlan.subtitle||'';$('planNote').value=state.drawerPlan.note||'';$('planIcon').value=state.drawerPlan.icon||'🛡️';$('planTheme').value=state.drawerPlan.theme||'blue';$('planSort').value=num(state.drawerPlan.sort_order);$('planActive').value=String(state.drawerPlan.active!==false);renderPills(state.drawerPlan.pills||[]);renderDrawerPackages(plan?state.vpnPackages.filter(x=>String(x.plan_id)===String(plan.id)):[]);$('packagesSection').classList.toggle('drawer-new',!plan);show('deletePlanBtn',!!plan);$('deletePlanBtn').dataset.id=plan?.id||'';$('planDrawer').classList.add('open');$('planDrawer').setAttribute('aria-hidden','false')}
function closePlanDrawer(){if(state.dirty){/* keep global dirty flag for other forms; drawer edits are not auto-persisted */}$('planDrawer').classList.remove('open');$('planDrawer').setAttribute('aria-hidden','true');state.drawerPlan=null}
function renderPills(pills){const w=$('pillEditor');w.innerHTML=(pills||[]).map((p,i)=>`<div class="pill-edit" data-pill-row="${i}"><input value="${esc(p?.title??p??'')}" placeholder="ویژگی"><button type="button" data-action="remove-pill" data-index="${i}">×</button></div>`).join('')||'<span style="font-size:9px;color:#6f879d">ویژگی‌ای ثبت نشده.</span>'}
function getPills(){return [...$('pillEditor').querySelectorAll('[data-pill-row] input')].map(x=>x.value.trim()).filter(Boolean).map(title=>({title}))}
function renderDrawerPackages(pk){const w=$('packageEditor');w.innerHTML=(pk||[]).map((x,i)=>packageRow(x,i)).join('')||'<div style="font-size:9px;color:#6f879d;padding:9px">هنوز پکیجی وجود ندارد.</div>'}
function packageRow(x={},i=0){const id=x.id??'';return `<div class="package-edit-row" data-package-row data-id="${id}" data-temp="${id?'false':'true'}"><label>عنوان<input data-field="label" value="${esc(x.label||'پکیج جدید')}"></label><label>قیمت تومان<input data-field="price_toman" type="number" min="0" value="${num(x.price_toman)}"></label><label>ترتیب<input data-field="sort_order" type="number" value="${num(x.sort_order,i+1)}"></label><label>وضعیت<select data-field="active"><option value="true" ${x.active!==false?'selected':''}>فعال</option><option value="false" ${x.active===false?'selected':''}>مخفی</option></select></label><div class="package-row-actions"><button type="button" class="icon-action" data-action="duplicate-package" title="کپی">⧉</button><button type="button" class="icon-action danger" data-action="remove-package" title="حذف">×</button></div></div>`}
function readPlanForm(){return {slug:$('planSlug').value.trim(),title:$('planTitle').value.trim(),subtitle:$('planSubtitle').value.trim(),note:$('planNote').value.trim(),icon:$('planIcon').value.trim()||'🛡️',theme:$('planTheme').value,sort_order:num($('planSort').value),active:$('planActive').value==='true',pills:getPills()}}
function readPackageRow(row){const v=k=>row.querySelector(`[data-field="${k}"]`)?.value??'';return {label:v('label').trim(),price_toman:num(v('price_toman')),sort_order:num(v('sort_order')),active:v('active')==='true'}}
async function savePlanDrawer(){const btn=$('savePlan');btn.disabled=true;try{const data=readPlanForm();if(!data.title||!data.slug)throw new Error('عنوان و Slug الزامی است.');let planId=num($('planId').value,0);if(planId){const {error}=await state.sb.from('vpn_plans').update(data).eq('id',planId);if(error)throw error}else{const {data:created,error}=await state.sb.from('vpn_plans').insert(data).select('id').single();if(error)throw error;planId=created.id}
for(const row of $('packageEditor').querySelectorAll('[data-package-row]')){const payload=readPackageRow(row);if(!payload.label)continue;const id=num(row.dataset.id,0);if(id){const {error}=await state.sb.from('vpn_packages').update(payload).eq('id',id);if(error)throw error}else{const {error}=await state.sb.from('vpn_packages').insert({...payload,plan_id:planId});if(error)throw error}}
toast('پلن و پکیج‌ها ذخیره شدند');closePlanDrawer();await loadAll()}catch(e){toast(errMessage(e),'error')}finally{btn.disabled=false}}
async function removePackage(row){const id=num(row.dataset.id,0);if(!id){row.remove();return}const ok=await confirmBox('حذف پکیج؟','این پکیج از فروشگاه حذف می‌شود.');if(!ok)return;const {error}=await state.sb.from('vpn_packages').delete().eq('id',id);if(error)return toast(error.message,'error');row.remove();state.vpnPackages=state.vpnPackages.filter(x=>Number(x.id)!==id);toast('پکیج حذف شد')}
async function deletePlan(id){const plan=state.vpnPlans.find(x=>Number(x.id)===Number(id));const ok=await confirmBox('حذف '+(plan?.title||'پلن')+'؟','تمام پکیج‌های این پلن هم حذف خواهند شد. این عملیات قابل بازگشت نیست.');if(!ok)return;const {error}=await state.sb.from('vpn_plans').delete().eq('id',id);if(error)return toast(error.message,'error');toast('پلن حذف شد');closePlanDrawer();await loadAll()}
async function togglePlan(id){const p=state.vpnPlans.find(x=>Number(x.id)===Number(id));if(!p)return;const {error}=await state.sb.from('vpn_plans').update({active:!p.active}).eq('id',id);if(error)return toast(error.message,'error');toast(!p.active?'پلن فعال شد':'پلن مخفی شد');await loadAll()}
function fillTelegram(){const s=state.store;$('starsBasis').value=s.stars_price_basis||'usdt';$('starUsdt').value=s.star_base_usdt??.015;$('starToman').value=s.star_base_toman??2880;$('starsMarkup').value=s.stars_markup??0;$('premiumMarkup').value=s.premium_markup??0;$('sliderMin').value=s.slider_min??50;$('sliderMax').value=s.slider_max??10000;$('sliderStep').value=s.slider_step??25;$('sliderPresets').value=(s.slider_presets||[]).join(', ')}
function renderPremium(){const w=$('premiumEditor');if(!w)return;w.innerHTML=state.premium.map(p=>`<div class="premium-row" data-premium="${p.id}"><div class="premium-row-head"><div><strong>${esc(p.label)}</strong><small>${p.months} ماه · Base ${p.base_usdt} USDT${p.markup_override!=null?' · '+p.markup_override+'% override':''}</small></div><div class="row-actions"><button class="icon-action" data-action="toggle-premium-edit">✎</button><button class="icon-action danger" data-action="delete-premium">×</button></div></div><div class="premium-edit hidden"><label>ماه<input data-p="months" type="number" value="${p.months}"></label><label>عنوان<input data-p="label" value="${esc(p.label)}"></label><label>Base USDT<input data-p="base_usdt" type="number" step="0.01" value="${p.base_usdt}"></label><label>Markup Override<input data-p="markup_override" type="number" min="0" step=".1" value="${p.markup_override??''}" placeholder="خالی = پیش‌فرض"></label><label>Badge<input data-p="badge" value="${esc(p.badge||'')}"></label><label>Featured<select data-p="featured"><option value="true" ${p.featured?'selected':''}>بله</option><option value="false" ${!p.featured?'selected':''}>خیر</option></select></label><label>وضعیت<select data-p="active"><option value="true" ${p.active?'selected':''}>فعال</option><option value="false" ${!p.active?'selected':''}>مخفی</option></select></label><button class="btn soft small" data-action="save-premium">ذخیره پلن</button></div></div>`).join('')||'<p class="helper">پلنی ثبت نشده.</p>'}
async function savePremium(row){const id=num(row.dataset.premium),v=k=>row.querySelector(`[data-p="${k}"]`)?.value??'';const ov=v('markup_override');const data={months:num(v('months')),label:v('label').trim(),base_usdt:num(v('base_usdt')),markup_override:ov===''?null:Math.max(0,num(ov)),badge:v('badge').trim()||null,featured:v('featured')==='true',active:v('active')==='true'};const {error}=await state.sb.from('premium_plans').update(data).eq('id',id);if(error)return toast(error.message,'error');toast('پلن Premium ذخیره شد');await loadAll()}
async function addPremium(){const next=(state.premium.at(-1)?.months||0)+1;const {error}=await state.sb.from('premium_plans').insert({months:next,label:next+' ماهه',base_usdt:1,featured:false,active:true});if(error)return toast(error.message,'error');await loadAll();toast('پلن Premium اضافه شد')}
async function deletePremium(id){if(!(await confirmBox('حذف پلن Premium؟','این پلن از صفحه فروشگاه حذف می‌شود.')))return;const {error}=await state.sb.from('premium_plans').delete().eq('id',id);if(error)return toast(error.message,'error');await loadAll();toast('پلن حذف شد')}
async function saveTelegram(){const data={stars_price_basis:$('starsBasis').value,star_base_usdt:num($('starUsdt').value),star_base_toman:num($('starToman').value),stars_markup:Math.max(0,num($('starsMarkup').value)),premium_markup:Math.max(0,num($('premiumMarkup').value)),slider_min:num($('sliderMin').value),slider_max:num($('sliderMax').value),slider_step:num($('sliderStep').value),slider_presets:list($('sliderPresets').value),updated_by:state.user.id};if(data.slider_max<=data.slider_min)return toast('حداکثر Slider باید بیشتر از حداقل باشد.','error');const {error}=await state.sb.from('store_settings').update(data).eq('id',1);if(error)return toast(error.message,'error');toast('تنظیمات Telegram ذخیره شد');await loadAll()}
function renderPricing(){const s=state.store;const basis=s.stars_price_basis==='toman'?fmt(s.star_base_toman)+' ت':Number(s.star_base_usdt||0).toFixed(4)+' USDT';$('pricingStarsBase').textContent=basis;$('pricingStarsMarkup').textContent=fmt(s.stars_markup)+'%';const sample=s.stars_price_basis==='toman'?1000*num(s.star_base_toman)*(1+num(s.stars_markup)/100):1000*num(s.star_base_usdt)*(1+num(s.stars_markup)/100)*num(s.fallback_usdt_toman);$('pricingStarsSample').textContent=fmt(sample)+' ت';$('pricingPremiumSummary').innerHTML=state.premium.map(p=>`<div><small>${esc(p.label)}</small><strong>${fmt(p.base_usdt)} USDT</strong></div>`).join('');$('smartRounding').checked=!!s.smart_rounding_enabled;$('roundSmall').value=s.round_small||5000;$('roundMedium').value=s.round_medium||10000;$('roundLarge').value=s.round_large||20000;$('fallbackRate').value=s.fallback_usdt_toman||192000}
async function savePricing(){const data={smart_rounding_enabled:$('smartRounding').checked,round_small:num($('roundSmall').value),round_medium:num($('roundMedium').value),round_large:num($('roundLarge').value),fallback_usdt_toman:num($('fallbackRate').value),updated_by:state.user.id};const {error}=await state.sb.from('store_settings').update(data).eq('id',1);if(error)return toast(error.message,'error');toast('قیمت‌گذاری ذخیره شد');await loadAll()}
function renderDiscounts(){const w=$('discountEditor');if(!w)return;w.innerHTML=state.discounts.map(d=>`<article class="discount-row" data-discount="${d.id}"><div class="discount-row-head"><div><strong>${esc(d.code)}</strong><small>${d.percent}% · ${esc(d.scope)} · ${d.enabled?'فعال':'خاموش'}${d.max_uses!=null?' · '+d.uses+'/'+d.max_uses:' '}</small></div><div class="row-actions"><button class="icon-action" data-action="toggle-discount-edit">✎</button><button class="icon-action danger" data-action="delete-discount">×</button></div></div><div class="discount-edit hidden"><label>Code<input data-d="code" value="${esc(d.code)}"></label><label>Percent<input data-d="percent" type="number" min="0" max="100" value="${d.percent}"></label><label>Scope<select data-d="scope"><option value="all" ${d.scope==='all'?'selected':''}>All</option><option value="vpn" ${d.scope==='vpn'?'selected':''}>VPN</option><option value="stars" ${d.scope==='stars'?'selected':''}>Stars</option><option value="premium" ${d.scope==='premium'?'selected':''}>Premium</option></select></label><label>Min order<input data-d="min_order" type="number" value="${d.min_order||0}"></label><label>Max uses<input data-d="max_uses" type="number" value="${d.max_uses??''}" placeholder="نامحدود"></label><label>Expires<input data-d="expires_at" type="datetime-local" value="${d.expires_at?new Date(d.expires_at).toISOString().slice(0,16):''}"></label><label>وضعیت<select data-d="enabled"><option value="true" ${d.enabled?'selected':''}>فعال</option><option value="false" ${!d.enabled?'selected':''}>خاموش</option></select></label><button class="btn soft small" data-action="save-discount">ذخیره کد</button></div></article>`).join('')||'<div class="panel-card">کد تخفیفی ثبت نشده.</div>'}
async function addDiscount(){const code='NEW'+Math.floor(1000+Math.random()*9000);const {error}=await state.sb.from('discount_codes').insert({code,percent:10,scope:'all',enabled:true,min_order:0});if(error)return toast(error.message,'error');await loadAll();toast('کد جدید ساخته شد')}
async function saveDiscount(row){const id=num(row.dataset.discount),v=k=>row.querySelector(`[data-d="${k}"]`)?.value??'';const mu=v('max_uses'),ex=v('expires_at');const data={code:v('code').trim().toUpperCase(),percent:num(v('percent')),scope:v('scope'),enabled:v('enabled')==='true',min_order:num(v('min_order')),max_uses:mu===''?null:num(mu),expires_at:ex?new Date(ex).toISOString():null};const {error}=await state.sb.from('discount_codes').update(data).eq('id',id);if(error)return toast(error.message,'error');toast('کد ذخیره شد');await loadAll()}
async function deleteDiscount(id){if(!(await confirmBox('حذف کد تخفیف؟','این کد دیگر قابل استفاده نخواهد بود.')))return;const {error}=await state.sb.from('discount_codes').delete().eq('id',id);if(error)return toast(error.message,'error');await loadAll();toast('کد حذف شد')}
function fillContent(){$('featuresJson').value=jsonText(state.content.features);$('faqJson').value=jsonText(state.content.faq);$('reviewsJson').value=jsonText(state.content.reviews);$('tutorialsJson').value=jsonText(state.content.tutorials);$('comparisonJson').value=jsonText(state.content.comparison)}
async function saveContent(){try{const data={features:JSON.parse($('featuresJson').value||'[]'),faq:JSON.parse($('faqJson').value||'[]'),reviews:JSON.parse($('reviewsJson').value||'[]'),tutorials:JSON.parse($('tutorialsJson').value||'[]'),comparison:JSON.parse($('comparisonJson').value||'[]'),updated_by:state.user.id};const {error}=await state.sb.from('content_settings').update(data).eq('id',1);if(error)throw error;toast('محتوا ذخیره شد');await loadAll()}catch(e){toast('JSON نامعتبر یا خطای ذخیره: '+errMessage(e),'error')}}
function fillStore(){const s=state.store;$('brandName').value=s.brand_name||'';$('brandSubtitle').value=s.brand_subtitle||'';$('heroTitle').value=s.hero_title||'';$('heroText').value=s.hero_text||'';$('supportUser').value=s.telegram_support||'';$('channelUser').value=s.telegram_channel||'';$('footerTextAdmin').value=s.footer_text||'';$('announcementEnabled').checked=!!s.announcement_enabled;$('announcementText').value=s.announcement_text||'';$('showReviews').checked=!!s.show_reviews;$('showTutorials').checked=!!s.show_tutorials;$('showComparison').checked=!!s.show_comparison}
async function saveStore(){const data={brand_name:$('brandName').value.trim(),brand_subtitle:$('brandSubtitle').value.trim(),hero_title:$('heroTitle').value.trim(),hero_text:$('heroText').value.trim(),telegram_support:$('supportUser').value.trim().replace(/^@/,''),telegram_channel:$('channelUser').value.trim().replace(/^@/,''),footer_text:$('footerTextAdmin').value.trim(),announcement_enabled:$('announcementEnabled').checked,announcement_text:$('announcementText').value.trim(),show_reviews:$('showReviews').checked,show_tutorials:$('showTutorials').checked,show_comparison:$('showComparison').checked,updated_by:state.user.id};const {error}=await state.sb.from('store_settings').update(data).eq('id',1);if(error)return toast(error.message,'error');toast('تنظیمات فروشگاه ذخیره شد');await loadAll()}
async function audit(){const {data,error}=await state.sb.from('audit_log').select('*').order('changed_at',{ascending:false}).limit(60);if(error)return toast(error.message,'error');$('auditList').innerHTML=(data||[]).map(x=>`<div class="audit-item"><div><strong>${esc(x.table_name||'change')} · ${esc(x.action||'UPDATE')}</strong><span>#${esc(x.row_id||'—')}</span></div><span>${new Date(x.changed_at).toLocaleString('fa-IR')} · ${esc(x.changed_by||'system')}</span></div>`).join('')||'<div class="audit-item">هنوز تغییری ثبت نشده.</div>'}
function goPane(name){document.querySelectorAll('.navbtn').forEach(x=>x.classList.toggle('active',x.dataset.pane===name));document.querySelectorAll('.pane').forEach(x=>x.classList.toggle('active',x.id==='pane-'+name));const meta=paneMeta[name]||[name,name];$('breadcrumb').textContent=meta[0];$('pageTitle').textContent=meta[1];if(name==='audit')audit();closeMobileSidebar();window.scrollTo({top:0,behavior:'smooth'})}
function openMobileSidebar(){$('sidebar').classList.add('open');$('sidebarBackdrop').classList.add('open')}
function closeMobileSidebar(){$('sidebar').classList.remove('open');$('sidebarBackdrop').classList.remove('open')}
function bindEvents(){document.addEventListener('click',async e=>{const t=e.target.closest('[data-action]');if(t){const a=t.dataset.action,id=num(t.dataset.id,0);if(a==='open-new-plan')openPlanDrawer();else if(a==='edit-plan')openPlanDrawer(id);else if(a==='toggle-plan')await togglePlan(id);else if(a==='close-plan-drawer')closePlanDrawer();else if(a==='add-pill'){const pills=getPills();pills.push({title:''});renderPills(pills);const inputs=$('pillEditor').querySelectorAll('input');inputs[inputs.length-1]?.focus()}else if(a==='remove-pill'){const row=t.closest('[data-pill-row]');row?.remove();if(!$('pillEditor').children.length)renderPills([])}else if(a==='add-package'){$('packageEditor').insertAdjacentHTML('beforeend',packageRow({},$('packageEditor').children.length));$('packageEditor').querySelector('div[style]')?.remove()}else if(a==='duplicate-package'){const row=t.closest('[data-package-row]');const d=readPackageRow(row);delete d.id;$('packageEditor').insertAdjacentHTML('beforeend',packageRow({...d,id:null},$('packageEditor').children.length))}else if(a==='remove-package')await removePackage(t.closest('[data-package-row]'));else if(a==='delete-plan')await deletePlan(id);else if(a==='delete-current-plan')await deletePlan(num(t.dataset.id));else if(a==='toggle-premium-edit')t.closest('.premium-row')?.querySelector('.premium-edit')?.classList.toggle('hidden');else if(a==='save-premium')await savePremium(t.closest('.premium-row'));else if(a==='delete-premium')await deletePremium(num(t.closest('.premium-row')?.dataset.premium));else if(a==='toggle-discount-edit')t.closest('.discount-row')?.querySelector('.discount-edit')?.classList.toggle('hidden');else if(a==='save-discount')await saveDiscount(t.closest('.discount-row'));else if(a==='delete-discount')await deleteDiscount(num(t.closest('.discount-row')?.dataset.discount));else if(a==='cancel-confirm')closeConfirm(false);return}
const jump=e.target.closest('[data-jump]');if(jump){goPane(jump.dataset.jump);if(jump.dataset.quick==='new-plan')setTimeout(()=>openPlanDrawer(),100);if(jump.dataset.quick==='new-discount')setTimeout(()=>addDiscount(),100)}
});
$('confirmYes').addEventListener('click',()=>closeConfirm(true));$('savePlan').addEventListener('click',savePlanDrawer);$('saveTelegram').addEventListener('click',saveTelegram);$('addPremium').addEventListener('click',addPremium);$('savePricing').addEventListener('click',savePricing);$('addDiscount').addEventListener('click',addDiscount);$('saveContent').addEventListener('click',saveContent);$('saveStore').addEventListener('click',saveStore);$('reloadAudit').addEventListener('click',audit);$('openSidebar').addEventListener('click',openMobileSidebar);$('closeSidebar').addEventListener('click',closeMobileSidebar);$('sidebarBackdrop').addEventListener('click',closeMobileSidebar);
document.querySelectorAll('.navbtn').forEach(b=>b.addEventListener('click',()=>goPane(b.dataset.pane)));document.querySelectorAll('.filter').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.vpnFilter=b.dataset.vpnFilter;renderVpn()}));$('vpnSearch').addEventListener('input',e=>{state.vpnQuery=e.target.value;renderVpn()});document.querySelectorAll('.content-tab').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.content-tab').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.content-json').forEach(x=>x.classList.toggle('active',x.dataset.contentPanel===b.dataset.contentTab))}));
for(const el of document.querySelectorAll('#dashboard input,#dashboard select,#dashboard textarea'))el.addEventListener('input',()=>setDirty(true));window.addEventListener('beforeunload',e=>{if(state.dirty){e.preventDefault();e.returnValue=''}})}
async function enter(u){state.user=u;show('login',false);show('denied',false);show('logout',true);try{if(!(await isAdmin())){show('denied',true);return}show('dashboard',true);adminNotice('در حال بارگذاری','اطلاعات فروشگاه از Supabase دریافت می‌شود…','loading');await loadAll()}catch(e){show('dashboard',true);adminNotice('خطا در اتصال پنل',errMessage(e),'error');toast(errMessage(e),'error')}}
async function init(){if(!configured()||!window.supabase?.createClient){show('setup',true);return}state.sb=window.supabase.createClient(BG_CONFIG.SUPABASE_URL,BG_CONFIG.SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true}});bindEvents();$('loginForm').addEventListener('submit',async e=>{e.preventDefault();$('loginError').textContent='';const btn=e.currentTarget.querySelector('button[type=submit]');btn.disabled=true;const {data,error}=await state.sb.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});btn.disabled=false;if(error)return $('loginError').textContent=error.message;await enter(data.user)});async function logout(){await state.sb.auth.signOut();location.reload()}$('logout').addEventListener('click',logout);$('deniedLogout').addEventListener('click',logout);const {data:{session}}=await state.sb.auth.getSession();if(session?.user)await enter(session.user);else show('login',true)}
document.addEventListener('DOMContentLoaded',init);
})();
