(function(){
const $=id=>document.getElementById(id);let order=null;let lastFocus=null;
function money(n){return Number(n||0).toLocaleString('en-US')+' تومان'}
function cryptoFmt(n,d){return n==null?'—':Number(n).toLocaleString('en-US',{maximumFractionDigits:d,minimumFractionDigits:d>1?Math.min(2,d):0})}
function id(prefix){const b=new Uint8Array(3);globalThis.crypto.getRandomValues(b);return 'BG-'+prefix+'-'+[...b].map(x=>x.toString(16).padStart(2,'0')).join('').toUpperCase()}
function receiptText(o){const lines=['🧾 سفارش BlueGate','','کد سفارش: '+o.id,'محصول: '+o.product,'انتخاب: '+o.variant,'قیمت پایه: '+money(o.subtotal)];if(o.discountPct)lines.push('تخفیف: '+o.discountPct+'٪'+(o.discountCode?' ('+o.discountCode+')':''));lines.push('مبلغ نهایی: '+money(o.final),'معادل: '+cryptoFmt(o.amounts.usdt,2)+' USDT','TRX: '+cryptoFmt(o.amounts.trx,2),'TON: '+cryptoFmt(o.amounts.ton,3),'نرخ تتر: '+money(o.rate),'زمان: '+o.timeText,'','درخواست خرید این سفارش را دارم.');return lines.join('\n')}
function scopeInfo(o){
  if(o.scope==='vpn')return {icon:'🛡️',badge:'BluePing VPN',className:'vpn',highlights:['اتصال پایدار','پشتیبانی سرویس','تحویل سریع']};
  if(o.scope==='stars')return {icon:'⭐',badge:'Telegram Stars',className:'stars',highlights:['مقدار دلخواه','قیمت لحظه‌ای','ارسال مستقیم']};
  return {icon:'✦',badge:'Telegram Premium',className:'premium',highlights:['اشتراک رسمی','فعال‌سازی سریع','پشتیبانی کامل']};
}
function renderHighlights(info){const host=$('productHighlights');if(!host)return;host.innerHTML=info.highlights.map(x=>`<span><i>✓</i>${x}</span>`).join('')}
function render(){if(!order)return;const info=scopeInfo(order);const modal=$('checkoutModal');modal.dataset.scope=info.className;$('checkoutProductIcon').dataset.scope=info.className;$('checkoutProductIcon').innerHTML=`<span>${info.icon}</span>`;$('scopeBadge').textContent=info.badge;$('scopeBadge').dataset.scope=info.className;renderHighlights(info);
  $('receiptId').textContent=order.id;$('receiptProduct').textContent=order.product;$('receiptVariant').textContent=order.variant;$('receiptSubtotal').textContent=money(order.subtotal);$('receiptTotal').textContent=Number(order.final).toLocaleString('en-US');$('receiptUsdt').textContent=cryptoFmt(order.amounts.usdt,2)+' USDT';$('receiptTrx').textContent=cryptoFmt(order.amounts.trx,2)+' TRX';$('receiptTon').textContent=cryptoFmt(order.amounts.ton,3)+' TON';$('receiptRate').textContent=money(order.rate);$('receiptTime').textContent=order.timeText;
  $('discountRow').classList.toggle('hidden',!order.discountPct);$('receiptDiscount').textContent=order.discountPct?'− '+money(order.subtotal-order.final)+' ('+order.discountPct+'٪)':'—';
  const saving=$('checkoutSaving');if(order.discountPct){saving.textContent='تبریک! '+money(order.subtotal-order.final)+' تخفیف روی این سفارش اعمال شد.';saving.classList.remove('hidden')}else saving.classList.add('hidden');
  const u=(order.telegram||'bluegatesupport').replace(/^@/,'');$('sendTelegram').href='https://t.me/'+encodeURIComponent(u)+'?text='+encodeURIComponent(receiptText(order))
}
function open(data){const prefix=data.scope==='vpn'?'VPN':data.scope==='stars'?'STAR':'PREM';lastFocus=document.activeElement;order={...data,id:id(prefix),subtotal:Number(data.toman),final:Number(data.toman),discountPct:0,discountCode:null,amounts:window.BGRates.amounts(data.toman,data.rates),rate:data.rates.usdt_toman,timeText:new Date().toLocaleString('fa-IR')};$('discountInput').value='';$('discountMessage').textContent='';$('discountPanel').classList.add('hidden');$('discountToggle').setAttribute('aria-expanded','false');$('discountToggle').querySelector('b').textContent='＋';render();$('checkoutModal').classList.remove('hidden');document.body.style.overflow='hidden';setTimeout(()=>$('modalClose')?.focus(),60)}
function close(){$('checkoutModal').classList.add('hidden');document.body.style.overflow='';lastFocus?.focus?.()}
function toggleDiscount(){const panel=$('discountPanel'),open=panel.classList.contains('hidden');panel.classList.toggle('hidden',!open);$('discountToggle').setAttribute('aria-expanded',String(open));$('discountToggle').querySelector('b').textContent=open?'−':'＋';if(open)setTimeout(()=>$('discountInput').focus(),80)}
async function apply(){if(!order)return;const code=$('discountInput').value.trim().toUpperCase();if(!code){$('discountMessage').textContent='اول کد تخفیف را وارد کن.';return}$('discountApply').disabled=true;try{const res=await window.BGApi.rpc('validate_discount',{p_code:code,p_scope:order.scope,p_amount:order.subtotal});const row=Array.isArray(res)?res[0]:res;if(!row?.valid)throw new Error(row?.message||'invalid');order.discountPct=Number(row.percent||0);order.discountCode=code;order.final=window.BGPricing.afterDiscount(order.subtotal,order.discountPct);order.amounts=window.BGRates.amounts(order.final,order.rates);$('discountMessage').textContent='✓ تخفیف '+order.discountPct+'٪ با موفقیت اعمال شد.';render()}catch(e){$('discountMessage').textContent='این کد معتبر نیست یا برای این محصول قابل استفاده نیست.'}finally{$('discountApply').disabled=false}}
async function copyText(text,button,done,original){try{await navigator.clipboard.writeText(text);if(button){button.textContent=done;setTimeout(()=>button.textContent=original,1200)}}catch(_){prompt('Copy',text)}}
async function copy(){if(!order)return;copyText(receiptText(order),$('copyReceipt'),'کپی شد ✓','کپی جزئیات سفارش')}
async function copyId(){if(!order)return;copyText(order.id,$('copyOrderId'),'✓','کپی')}
document.addEventListener('DOMContentLoaded',()=>{$('modalClose').addEventListener('click',close);document.querySelector("[data-close='1']").addEventListener('click',close);$('discountToggle').addEventListener('click',toggleDiscount);$('discountApply').addEventListener('click',apply);$('copyReceipt').addEventListener('click',copy);$('copyOrderId').addEventListener('click',copyId);$('discountInput').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();apply()}});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('checkoutModal').classList.contains('hidden'))close()})});window.BGCheckout={open,close};
})();
