(function(){
const $=id=>document.getElementById(id);let order=null;
function money(n){return Number(n||0).toLocaleString('en-US')+' تومان'}
function cryptoFmt(n,d){return n==null?'—':Number(n).toLocaleString('en-US',{maximumFractionDigits:d,minimumFractionDigits:d>1?Math.min(2,d):0})}
function id(prefix){const b=new Uint8Array(3);globalThis.crypto.getRandomValues(b);return 'BG-'+prefix+'-'+[...b].map(x=>x.toString(16).padStart(2,'0')).join('').toUpperCase()}
function receiptText(o){const lines=['🧾 سفارش BlueGate','','شماره سفارش: '+o.id,'محصول: '+o.product,'انتخاب: '+o.variant,'مبلغ: '+money(o.final)];if(o.discountPct)lines.push('تخفیف: '+o.discountPct+'٪'+(o.discountCode?' ('+o.discountCode+')':''));lines.push('معادل: '+cryptoFmt(o.amounts.usdt,2)+' USDT','TRX: '+cryptoFmt(o.amounts.trx,2),'TON: '+cryptoFmt(o.amounts.ton,3),'نرخ تتر: '+money(o.rate),'زمان: '+o.timeText,'','درخواست خرید این سفارش را دارم.');return lines.join('\n')}
function render(){if(!order)return;$('receiptId').textContent=order.id;$('receiptProduct').textContent=order.product;$('receiptVariant').textContent=order.variant;$('receiptSubtotal').textContent=money(order.subtotal);$('receiptTotal').textContent=Number(order.final).toLocaleString('en-US');$('receiptUsdt').textContent=cryptoFmt(order.amounts.usdt,2)+' USDT';$('receiptTrx').textContent=cryptoFmt(order.amounts.trx,2)+' TRX';$('receiptTon').textContent=cryptoFmt(order.amounts.ton,3)+' TON';$('receiptRate').textContent=money(order.rate);$('receiptTime').textContent=order.timeText;$('discountRow').classList.toggle('hidden',!order.discountPct);$('receiptDiscount').textContent=order.discountPct?order.discountPct+'٪':'—';const u=(order.telegram||'bluegatesupport').replace(/^@/,'');$('sendTelegram').href='https://t.me/'+encodeURIComponent(u)+'?text='+encodeURIComponent(receiptText(order))}
function open(data){const prefix=data.scope==='vpn'?'VPN':data.scope==='stars'?'STR':'PRM';order={...data,id:id(prefix),subtotal:Number(data.toman),final:Number(data.toman),discountPct:0,discountCode:null,amounts:window.BGRates.amounts(data.toman,data.rates),rate:data.rates.usdt_toman,timeText:new Date().toLocaleString('fa-IR')};$('discountInput').value='';$('discountMessage').textContent='';render();$('checkoutModal').classList.remove('hidden');document.body.style.overflow='hidden'}
function close(){$('checkoutModal').classList.add('hidden');document.body.style.overflow=''}
async function apply(){if(!order)return;const code=$('discountInput').value.trim().toUpperCase();if(!code){$('discountMessage').textContent='کد را وارد کن.';return}$('discountApply').disabled=true;try{const res=await window.BGApi.rpc('validate_discount',{p_code:code,p_scope:order.scope,p_amount:order.subtotal});const row=Array.isArray(res)?res[0]:res;if(!row?.valid)throw new Error(row?.message||'invalid');order.discountPct=Number(row.percent||0);order.discountCode=code;order.final=window.BGPricing.afterDiscount(order.subtotal,order.discountPct);order.amounts=window.BGRates.amounts(order.final,order.rates);$('discountMessage').textContent='تخفیف '+order.discountPct+'٪ اعمال شد.';render()}catch(e){$('discountMessage').textContent='کد تخفیف معتبر نیست یا برای این محصول قابل استفاده نیست.'}finally{$('discountApply').disabled=false}}
async function copy(){if(!order)return;const text=receiptText(order);try{await navigator.clipboard.writeText(text);$('copyReceipt').textContent='کپی شد ✓';setTimeout(()=>$('copyReceipt').textContent='کپی رسید',1200)}catch(_){prompt('Copy',text)}}
document.addEventListener('DOMContentLoaded',()=>{$('modalClose').addEventListener('click',close);document.querySelector("[data-close='1']").addEventListener('click',close);$('discountApply').addEventListener('click',apply);$('copyReceipt').addEventListener('click',copy);document.addEventListener('keydown',e=>{if(e.key==='Escape')close()})});window.BGCheckout={open,close};
})();
